### ISSUE TITLE
add cmd.msL Windows AutoPilot

### ISSUE THREAD

**Issue by dungadaman** [merill/cmd#109]
**Proposed name of the new command**
Windows AutoPilot

**Description**
Microsoft Intune admin center

**Category**
Devices

**Url**
https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesEnrollmentMenu/~/windowsEnrollment

**Comment by merill** [comment]
Available as inenroll.cmd.ms
