### ISSUE TITLE
Add Azure Workbooks

### ISSUE THREAD

**Issue by abul-boshor-doherty** [merill/cmd#110]
**Proposed name of the new command**
workbooks.cmd.ms

**Description**
Azure Workbooks

**Category**
Azure Workbooks

**Url**
https://portal.azure.com/?feature.msaljs=true#view/HubsExtension/BrowseResource/resourceType/microsoft.insights%2Fworkbooks

**Comment by merill** [comment]
Added as azwb.cmd.ms
