### ISSUE TITLE
Entra License command alias

### ISSUE THREAD

**Issue by itazlin** [merill/cmd#136]
**Proposed name of the new command**
enlic.cmd.ms or lic.cmd.ms

**Description**
Microsoft Entra
**Category**
Entra
**Url**
https://entra.microsoft.com/#view/Microsoft_AAD_IAM/LicensesMenuBlade/~/Overview/Microsoft_AAD_IAM/LicensesMenuBlade

**Comment by merill** [comment]
This is already available as enlicense.cmd.ms
