### ISSUE TITLE
Azure DNS command

### ISSUE THREAD

**Issue by keithmweaver** [merill/cmd#137]
**Proposed name of the new command**
azdns.cmd.ms

**Description**
DNS zones

**Category**
Azure

**Url**
https://portal.azure.com/#browse/Microsoft.Network%2FdnsZones

**Comment by merill** [comment]
Added. Thanks for submitting!

**Comment by keithmweaver** [comment]
The command that was added on the cmd.ms site is https://azdns.cmd.ms.cmd.ms. It should be https://azdns.cmd.ms

**Comment by merill** [comment]
Oops fixed. Thanks!
