### ISSUE TITLE
Adopt new cloud.microsoft URL's like https://admin.cloud.microsoft/exchange?

### ISSUE THREAD

**Issue by grimson73** [merill/cmd#143]
Hi,

https://techcommunity.microsoft.com/t5/exchange-team-blog/new-url-for-exchange-admin-center-eac-in-exchange-online/ba-p/4270023
As the Exchange Team blog states it will introduce a new URL to the Admin pages.
It seems several admin pages are migrating to the cloud.microsoft domain so I would suggest changing them here as well to get used to the new cloud.microsoft domain?

**Comment by merill** [comment]
Renamed exchange to cloud.microsoft
