### ISSUE TITLE
Azure devops portal link addition

### ISSUE THREAD

**Issue by kunalworldwide** [merill/cmd#64]
**dev.cmd.ms**
If this is for a blade within a portal, add the product prefix before the command (e.g. adxxxx).

**Azure DevOps Portal**
Title/Description of the command (use the same name shown in the Microsoft portal).

**Azure**
Name of the portal this blade lives in or the service name.

**https://dev.azure.com**
The url this command should redirect to.

**Comment by merill** [comment]
Done

**Comment by kunalworldwide** [comment]
Thanks
