### ISSUE TITLE
Microsoft Team Room Pro Portal

### ISSUE THREAD

**Issue by Mark-Goodwin84** [merill/cmd#67]
**Proposed name of the new command**
The new command allows you to access the MSFT Teams Room Pro Portal, That allows you to mange devices that have been assigned the Team Room Pro Licence

**Description**
Teams Rooms Pro Management portal

**Category**
M365 Admin Portal / Microsoft Teams 

**Url**
https://portal.rooms.microsoft.com/

**Comment by merill** [comment]
Done
