### ISSUE TITLE
Microsoft Teams Rooms Pro Management

### ISSUE THREAD

**Issue by halderex** [merill/cmd#70]
**Proposed name of the new command**
rooms

**Description**
Microsoft Teams Rooms Pro Management

The Microsoft Teams Rooms Pro Management service is a cloud-based management solution that proactively monitors and updates Microsoft Teams Rooms devices and their peripherals. The Pro management solution is for organizations looking to optimize meeting room experience for end users and rapidly scale their footprint enabled by real-time monitoring and management for Microsoft Teams Rooms devices.

**Category**
Microsoft Teams

**Url**
https://portal.rooms.microsoft.com/

**Comment by merill** [comment]
Done
