### ISSUE TITLE
Intune Proactive Remediations have moved, link is wrong

### ISSUE THREAD

**Issue by flotpg** [merill/cmd#97]
![CleanShot 2023-08-25 at 22 16 51@2x](https://github.com/merill/cmd/assets/20798074/436e77e2-1f59-4ab3-8035-191cda486c25)

It's under Devices > Remediations now (not under "hidden" under Endpoint analytics anymore).

Thanks and best regards. Keep up the great work :=
Flo.

**Comment by BurgerhoutJ** [comment]
I added this to a pull request, but I noticed this as well.

**Comment by merill** [comment]
Cheers thanks both. This has been merged now.

**Comment by the-project-group** [comment]
Works, thank @merill
